### PR TITLE
Attach container after initialization

### PR DESCRIPTION
**Pull request by FlorianWilhelm**
@abravalheri, so this is basically the functionality that allows attaching a container after the instantiation.

### CODE REVIEW

**Comment by FlorianWilhelm** [comment]
@abravalheri, okay, I am a bit lost regarding the remaining type errors, do you have an idea?

**Review by abravalheri — APPROVED** [review]
I think the BlockBuilder accept a section object in the `section` method as well (not only a string), so probably we want to call the `attach` there as well.

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, I think the type errors are probably related to #36.

When I introduced the typing annotations they were very complicated to get it right because the cyclic dependency between blocks and containers.

I think the easiest way around is to use the approach I used in #36 and remove the the type parameter from block and make some of the polymorphic methods invariant.

**Comment by FlorianWilhelm** [comment]
@abravalheri, please feel free to merge if this PR is fine with you.

**Pull request merged**
