### PR TITLE
Replace sphinx with mkdocs and move setup.cfg to pyproject.toml

### PR DESCRIPTION
**Pull request by FlorianWilhelm**
Trying to fix those Sphinx warnings from #90 one way or another.

### CODE REVIEW

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, thank you very much for the huge amount of work you are pouring into this...

Do we need to pull in `hatch` for this job?

Would [ignore the warnings](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-suppress_warnings) be a valid option for handling this problem? If this problem was reported in `sphinx` maybe it will eventually be fixed?

**Comment by FlorianWilhelm** [comment]
@abravalheri, `hatch` is not needed and I think we should keep it to setuptools only as PyScaffold does it the same way. I thought I give the new setuptools features a test run and also mkdocs for this. mkdocs really is so much easier to handle compared to Sphinx... but I can of course understand if it would give a wrong message if configupdater was using mkdocs and PyScaffold not. So I am completely open and would follow your suggestion. 

There are mainly 2 questions:
1) Should we adapt `pyproject.toml`-only using setuptools to have a test run for the next PyScaffold version?
2) Should we replace Sphinx with `mkdocs`? Maybe to also evaluate as it might be a way more lightweight alternative to Sphinx for an upcoming PyScaffold release. It's the first time I am trying `mkdocs` with RTD and it seems to work just fine.

1) and 2) are rather independent of each other. We could also just keep it as it is. Your call :-)

**Comment by FlorianWilhelm** [comment]
@abravalheri: Regarding ignoring the warnings, I am not sure it really is considered a bug in Sphinx napoleon, from all I understand I would rather say it's a kind of design decision for them but I might also be wrong.

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm,

> Should we adapt pyproject.toml-only using setuptools to have a test run for the next PyScaffold version?

Definitely! There is some initial work contributed to the [dev branch](https://github.com/pyscaffold/pyscaffold/tree/dev), but I have been very slow lately :P 

> Should we replace Sphinx with mkdocs? Maybe to also evaluate as it might be a way more lightweight alternative to Sphinx for an upcoming PyScaffold release. It's the first time I am trying mkdocs with RTD and it seems to work just fine.

I have no objection on that front, in fact we can use this opportunity and extract templates either for PyScaffold itself or `pyscaffoldext-mkdocs`.

Do you know what are the main advantages of mkdocs over sphinx+MyST?
I was really impressed by the work that the Executable Books team has been doing with Sphinx and MyST lately, and the fact that integrates smoothly with jupyter.

**Comment by abravalheri** [comment]
> Regarding ignoring the warnings, I am not sure it really is considered a bug in Sphinx napoleon

It seems that there are a [few issues](https://github.com/sphinx-doc/sphinx/issues?q=is%3Aissue+is%3Aopen+more+than+one+target+found+for+cross-reference+%27) open in sphinx that might be related to this. [One of them](https://github.com/sphinx-doc/sphinx/issues/4961) seem to have some traction and the overall idea seems to be supported by the leading dev (although no implementation is available yet).

> from all I understand I would rather say it's a kind of design decision for them but I might also be wrong.

Yes that is probably `sphinx` nudging that `apidoc` is a great start, but that probably when a project gets bigger, exposing just a subset of public APIs via `autodoc` results in a "more controlled" outcome...

**Pull request closed without merging**
