### PR TITLE
Fix type errors

### PR DESCRIPTION
**Pull request by FlorianWilhelm**
Fix type errors after latest changes in mypy it seems.

### CODE REVIEW

**Comment by FlorianWilhelm** [comment]
@abravalheri, hi there & and merry Christmas somewhat delayed ;-) 

Seems like mypy got more powerful again and finds the tiniest little type errors. Not sure about my fix though. Using an empty list instead of None works here when dealing with empty option values?

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, merry Christmas!

That is a though one 😋 Thank you very much for identifying it...

I think we can imagine the following (already existing) test as a regression test for the empty option values, what do you think? Is there any other test missing?

https://github.com/pyscaffold/configupdater/blob/29e8fb1306a8cedb97563ab6afc517b67623274a/tests/test_configupdater.py#L720-L729

Since it is passing the approach you took should be fine...

Alternatively, we could simply disable the type checking for the parsing function and assume that it is correct, coming from the stdlib...

**Review by abravalheri — APPROVED** [review]

**Comment by FlorianWilhelm** [comment]
Thanks @abravalheri, so looks like we got this covered already. Reading the code again, I think this is fine and beforehand it definitely was not 100% correct as we would use `.append` without verifying that it's not `None`. 
I got a better feeling if we don't deactivate type checks, could also be a mistake directly in the stdlib, who knows, the code of `configparser.py` was never really nice.

**Comment by abravalheri** [comment]
Yeah, I totally agree.

At this stage I think ConfigUpdater test suite is much more complete and exhaustive than stdlib's...

**Pull request merged**
